# Support HQ. V Netlify: Base directory = apps/support.

[build]
  command = "bash ../../tool/netlify_flutter_build.sh apps/support"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
